name: CI

on:
  push:
    branches: [ main, feature/odometry ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 src/mobile_robotics

      - name: Validate ROS msgs
        run: |
          source /opt/ros/foxy/setup.bash
          ros2 interface show CustomPose
